"""Domain models for Command Center."""

from .deal_models import (
    DealBase,
    OverdueDeal,
    StuckDeal,
    OrderReceivedAnalysis,
    ComplianceStatus,
    DealSummary,
    DealNote,
    DealActivity,
    DealFile,
    DealComment,
    DealSearchResult,
    # Stage History Models
    StageTransition,
    DealStageHistory,
    StagePerformanceMetrics,
    # CEO Radar Summary Models
    OverdueSnapshot,
    PMOverduePerformance,
    CEOInterventionDeal,
    OverdueSummaryResponse,
    StuckSnapshot,
    PMStuckControl,
    WorstStuckDeal,
    StageBottleneck,
    StuckSummaryResponse,
    OrderReceivedSnapshot,
    PMPipelineAcceleration,
    BlockersChecklistSummary,
    FastWinDeal,
    OrderReceivedSummaryResponse,
)
from .cashflow_models import (
    CashflowBucket,
    # LLM-powered prediction models
    DealForPrediction,
    PredictionOptions,
    CashflowPredictionInput,
    ForecastOptions,
    DealPrediction,
    PredictionMetadata,
    CashflowPredictionResult,
    ForecastPeriod,
    ForecastTotals,
    ForecastTable,
    AssumptionsReport,
)
from .kpi_models import OwnerKPI
from .dashboard_models import DashboardItem
from .email_models import DealIssue, EmailDraft
from .writer_models import (
    # Input contexts
    EmailDraftContext,
    ReminderDraftContext,
    DealSummaryContext,
    ComplianceContext,
    OrderReceivedContext,
    NoteSummaryContext,
    # Output results
    DraftEmailResult,
    DraftReminderResult,
    DealSummaryResult,
    ComplianceResult,
    OrderReceivedResult,
    NoteSummaryResult,
)

__all__ = [
    "DealBase",
    "OverdueDeal",
    "StuckDeal",
    "OrderReceivedAnalysis",
    "ComplianceStatus",
    "DealSummary",
    "DealNote",
    "DealActivity",
    "DealFile",
    "DealComment",
    "DealSearchResult",
    "CashflowBucket",
    "OwnerKPI",
    "DashboardItem",
    "DealIssue",
    "EmailDraft",
    # Stage History Models
    "StageTransition",
    "DealStageHistory",
    "StagePerformanceMetrics",
    # CEO Radar Summary Models
    "OverdueSnapshot",
    "PMOverduePerformance",
    "CEOInterventionDeal",
    "OverdueSummaryResponse",
    "StuckSnapshot",
    "PMStuckControl",
    "WorstStuckDeal",
    "StageBottleneck",
    "StuckSummaryResponse",
    "OrderReceivedSnapshot",
    "PMPipelineAcceleration",
    "BlockersChecklistSummary",
    "FastWinDeal",
    "OrderReceivedSummaryResponse",
    # Cashflow Prediction Models
    "DealForPrediction",
    "PredictionOptions",
    "CashflowPredictionInput",
    "ForecastOptions",
    "DealPrediction",
    "PredictionMetadata",
    "CashflowPredictionResult",
    "ForecastPeriod",
    "ForecastTotals",
    "ForecastTable",
    "AssumptionsReport",
    # Writer Service Models
    "EmailDraftContext",
    "ReminderDraftContext",
    "DealSummaryContext",
    "ComplianceContext",
    "OrderReceivedContext",
    "NoteSummaryContext",
    "DraftEmailResult",
    "DraftReminderResult",
    "DealSummaryResult",
    "ComplianceResult",
    "OrderReceivedResult",
    "NoteSummaryResult",
]